apiVersion: v2
name: external-dns-dnsserver-webhook
description: |
  external-dns-dnsserver-webhook is an external-dns webhook provider that configures an in-process DNS server.
type: application
version: 0.0.0-unknown
appVersion: 0.0.0-unknown
dependencies:
- name: external-dns
  version: 1.19.0
  repository: https://kubernetes-sigs.github.io/external-dns/
