service:
  type: ClusterIP
  annotations: {}
  port: 53
  targetPort: 5353

external-dns:
  provider:
    name: webhook
    webhook:
      image:
        repository: ghcr.io/frantjc/external-dns-dnsserver-webhook
        tag: 0.1.1
      args:
        - --debug
        - --dns-port=5353
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        runAsNonRoot: true
        runAsGroup: 1001
        runAsUser: 1001
